apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-app-2
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: config
    repoURL: https://github.com/testcodefresh/cf-e2e-rl-flow-apps.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: test-ns-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
